Pkg.add("Gadfly")
Pkg.add("Cairo")
Pkg.add("ApproxFun")
Pkg.add("IJulia")
Pkg.add("Winston")
Pkg.add("PyPlot")
Pkg.add("RDatasets")
Pkg.add("MultivariateStats")
Pkg.add("HypothesisTests")
Pkg.add("GLM")
Pkg.add("MLBase")
Pkg.add("Clustering")
Pkg.add("NMF")
Pkg.add("MCMC")
Pkg.add("TimeSeries")
Pkg.add("RegERMs")
Pkg.add("Stan")
Pkg.add("JuMP")
Pkg.add("NLopt")
Pkg.add("OpenCL")
Pkg.add("Optim")
Pkg.add("DataStructures")
Pkg.add("ODE")
Pkg.add("JSON")
Pkg.add("IterativeSolvers")
Pkg.add("FunctionalCollections")
Pkg.add("Combinatorics")
Pkg.add("ArrayViews")
Pkg.add("Graphs")
Pkg.add("Sundials")
Pkg.add("Roots")

Pkg.build("IJulia")
Pkg.build("HDF5")

print("\nNote that:::")
print("\tUse Pkg.installed() to check packages installed, &")
print("\tUse Pkg.update() to update all installed packages.")
print("\nTo use IJulia notebook:::")
print("\tusing IJulia; notebook()")
